// <auto-generated />
using Bunkong.WorkLogs.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bunkong.WorkLogs.DAL.Migrations
{
    [DbContext(typeof(BunKongDbContext))]
    [Migration("20180520024229_add-test-db-migration")]
    partial class addtestdbmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bunkong.WorkLogs.DAL.TestTwoDbContextMigrateTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("TestTwoDbContextMigrateTable");
                });

            modelBuilder.Entity("Bunkong.WorkLogs.DAL.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Remark")
                        .HasMaxLength(90);

                    b.Property<string>("WorkContent")
                        .HasMaxLength(500);

                    b.Property<DateTime>("WorkDate");

                    b.Property<double>("WorkHoures");

                    b.HasKey("Id");

                    b.ToTable("WorkLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
