// <auto-generated />
using Bunkong.WorkLogs.Database.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bunkong.WorkLogs.Database.MySql.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20180527023124_MySql_WorkLogTable")]
    partial class MySql_WorkLogTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Bunkong.WorkLogs.Database.Schema.WorkLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60);

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Remark")
                        .HasMaxLength(90);

                    b.Property<string>("WorkContent")
                        .HasMaxLength(500);

                    b.Property<DateTime>("WorkDate");

                    b.Property<double>("WorkHoures");

                    b.HasKey("Id");

                    b.ToTable("WorkLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
